### ISSUE TITLE
cannot import name 'BUFRWriter'

### ISSUE THREAD

**Issue by khintz** [jdkloe/pybufr-ecmwf#13]
I was reading the USAGE.md file for examples how to use this excellent software. However, I can not import BUFRWriter, but I am able to import BUFRReader. Is the documentation outdated or is this a bug?

`>>> from pybufr_ecmwf.bufr import BUFRWriter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'BUFRWriter'
>>> from pybufr_ecmwf.bufr import BUFRReader
`

**Comment by jdkloe** [comment]
Hi, thanks for your feedback.
As the software evolves, I try to keep the documentation updated to the latest software version in github. This also means that it may differ with older published versions like the release versions on pypi. Older versions should have their own usage file (below the docs folder after unpacking the source code).
Also the BUFRWriter class is a fairly new development, and was not yet available in release version 0.82.
Could you please tell me which software version you use and how you obtained it? Then I probably can give you some pointers on how to write BUFR files from python.
If needed (or more convenient) I can also make a new release so you can install the latest version (that has BUFRWriter) with for example a tool like pip.

**Comment by jdkloe** [comment]
cleaning up the issue list, I consider this nit to be a bug, since the documentation for the current githuib version matches the code.
