### ISSUE TITLE
RADAR RAINFALL INTENSITY

### ISSUE THREAD

**Issue by DivinytyToffee** [jdkloe/pybufr-ecmwf#18]
Hi.  I have a question, how calculated RADAR RAINFALL INTENSITY and always it have m/s as units? May be it's mm/h?

**Comment by jdkloe** [comment]
Hi,
to determine if this is a problem in your script, in the pybufr-ecmwf module, or in the BUFR tables used for decoding, I need some more information:
* a sample BUFR file that shows the problem
* a minimal excerpt from your script that shows this problem
* if applicable, a copy of the BUFR tables that you used for decoing.

**Comment by DivinytyToffee** [comment]
I used a default tables. My PM saying me what a "SPEED OF MOTION OF FEATURE" must be in mm/h, and asking how calculate this value. 
Can I just divide or multiple current value for make this value in mm/h, or if I use local tables this value recalculate in mm/h? 
```
SHORT STATION OR SITE NAME - 1005.0 - CCITTIA5
STATION OR SITE NAME - 2020.0 - CCITTIA5
LATITUDE (COARSE ACCURACY) - 59.94 - DEGREE
LONGITUDE (COARSE ACCURACY) - 30.7 - DEGREE
HEIGHT OF STATION (SEE NOTE 1) - 110.0 - M
DRY-BULB TEMPERATURE AT 2 M - 272.9 - K
VERTICAL SOUNDING SIGNIFICANCE - 2.0 - FLAG TABLE 8001
HEIGHT OR ALTITUDE - 0.0 - M
VERTICAL SOUNDING SIGNIFICANCE - 2.0 - FLAG TABLE 8001
HEIGHT OR ALTITUDE - 0.0 - M
DIRECTION OF MOTION OF FEATURE - 23.0 - DEGREE TRUE
SPEED OF MOTION OF FEATURE - 11.52 - M/S
PROJECTION TYPE - 3.0 - CODE TABLE 29001
PICTURE TYPE - 6.0 - CODE TABLE 30031
NUMBER OF PIXELS PER ROW - 100.0 - NUMERIC
NUMBER OF PIXELS PER COLUMN - 100.0 - NUMERIC
PIXEL SIZE ON HORIZONTAL - 1 - 4000.0 - M
PIXEL SIZE ON HORIZONTAL - 2 - 4000.0 - M
NUMBER OF RETRIEVED LAYERS - 1.0 - NUMERIC
DIMENSIONAL SIGNIFICANCE - 2.0 - CODE TABLE 8007
EXTENDED DELAYED DESCRIPTOR REPLICATION FACTOR - 494.0 - NUMERIC
EXTENDED DELAYED DESCRIPTOR AND DATA REPETITION FACTOR - 43.0 - NUMERIC
RADAR RAINFALL INTENSITY - 0.0 - M/S
```
[2020.0__2019-03-15_04-10-10__2019-03-15_04-21-16.zip](https://github.com/jdkloe/pybufr-ecmwf/files/3002044/2020.0__2019-03-15_04-10-10__2019-03-15_04-21-16.zip)

**Comment by jdkloe** [comment]
thanks for your sample file.
I can confirm that I also get unit m/s for rainfall intensity if I decode this sample file using pybufr-ecmwf.
Don't know yet why. It seems wrong to me as well. I don't think doing a unit conversion is a solution here.
I see that the bufr_dump tool that is included in the eccodes package (v.2.9.2) gives an error on this file:
```
bufr_dump 2020.0__2019-03-15_04-10-10__2019-03-15_04-21-16.bufr
{ "messages" : [ 
ERROR: unable to unpack data section: Decoding invalid (message=1)
```
so this suggests something is wrong, either with the file or the bufr tables.
Did you try to use any other decoding software on this file?

From previous users having trouble with radar data bufr files I remember that some of them need to be decoded with a non-standard (local) set of bufr tables. Maybe you could inquire with the producer of this file to see if this is the case?

**Comment by DivinytyToffee** [comment]
Thanks, for answer. No, I don't used another decoding software for decode this. But I suppose, what a producer using local configure table. Can you demonstrate how I can add local table?

**Comment by jdkloe** [comment]
Hi,
to use local BUFR tables you have to just place them in some subdirectory and set the following environment setting before using the software:
export BUFR_TABLES=<location of BUFR tables>

In addition, if you don't have the tables but do have a description of the template in a document, you can create a custom set of BUFR tables. An example of how to do this is given in:
example_programs/use_custom_tables_for_encoding.py [for encoding only]
and
test/test_delayed_repetition.py [for encoding and decoding]
test/test_delayed_replication.py [for encoding and decoding]

**Comment by DivinytyToffee** [comment]
Question to post scriptum. What F X Y link for ECHO TOPS?

**Comment by jdkloe** [comment]
Hi, sorry for my late response (I have been away for the last week and had no opportunity to work on this).
As for your question, I am no expert on rain radar, so you should double check with someone more informed. Looking at the default BUFR tables provided in the bufrdc_000409 library (which is the basis of pybufr-ecmwf) the descriptor 021021 is normally used for 'ECHO TOPS', so F=0, X=21 and Y=021.
See also page 77 in: http://www.wmo.int/pages/prog/www/WMOCodes/WMO306_vI2/LatestVERSION/WMO306_vI2_BUFRCREX_TableB_en.pdf

**Comment by jdkloe** [comment]
Is this problem now solved for you?
Can I close this issue?

**Comment by jdkloe** [comment]
no response for over a year. closing.
Feel free to reopen if this still is a problem for you.
