### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by sebhahn** [jdkloe/pybufr-ecmwf#21]
Are there any plans to support Python versions > 3.6?

At the moment installations via conda fails with e.g. Python 3.8

**Comment by jdkloe** [comment]
Yes, if my time allows I will try to get it to build for more recent pythons. But at this moment I cannot give you a date when that will be.

**Comment by jdkloe** [comment]
Latest git version has now been updated to compile again with python 3.8, 3.9 and 3.10 and more recent numpy versions.
