### ISSUE TITLE
Add even more convenient read only interface

### ISSUE THREAD

**Issue by cpaulik** [jdkloe/pybufr-ecmwf#3]
We've got a `BUFRReader` class based on `pybufr-ecmwf` that makes it fairly straightforward to read BUFR files.
#### example usage

``` python
latitude = []
longitude = []

with bufr_reader.BUFRReader(self.filename) as bufr:
    for message in bufr.messages():

        latitude.append(message[:, 12])
        longitude.append(message[:, 13])
```

You can find the source code [here](https://github.com/TUW-GEO/pytesmo/blob/master/pytesmo/io/bufr/bufr.py#L47). It uses the guessing of the array size as you have explained it in one of the examples. At the moment it is only tested on BUFR files we are actively using like the ASCAT Level-2 BUFR files from EUMETSAT.

Would you be interested to adding this to the library? I'm trying to focus our packages on their core functionality and move non-core functionality into appropriate packages.

If so then I can open a PR and we can talk about possible improvements.

**Comment by jdkloe** [comment]
Hi Christoph,

thanks for your offer, and yes I would welcome a pull request.
Also if other interface details can be improved I would be happy to discuss this with you. 

I am aware of the fact that the code is still rough around the edges, and maybe not so easy to use, so any discussion on what you would expect or like to have will give me a chance to improve it.

Best regards,

Jos
